/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dgioznfjujkxewrskgtf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5Y2ZxZXltZHNqeXVsZXh3cmxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyMzMxOTksImV4cCI6MjA4NTgwOTE5OX0.09Wb1CQwJjsmI-WfJPE-VUBUky_KrR5PFsOoHpGVkQo"
